export const RECEIVED_CITIES = "RECEIVED_CITIES";
export const RECEIVED_VEHICLES = "RECEIVED_VEHICLES";
export const VEHICLE_SELECTED = "VEHICLE_SELECTED";
export const CITY_SELECTED = "CITY_SELECTED";